version: '3.9'

networks:
  assessment-network:
    driver: bridge
    name: assessment-network

volumes:
  redis-data:
    name: assessment_redis-data
  rabbitmq-data:
    name: assessment_rabbitmq-data

services:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'rabbitmq'
    restart: always
    ports:
      - "15672:15672"
      - "15671:15671"
      - "5672:5672"
    networks:
      - assessment-network
    volumes:
      - rabbitmq-data:/data:delegated

  redis:
    build:
      context: ./docker/redis
      dockerfile:
        Dockerfile
    restart: always
    platform: linux/amd64
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    networks:
      - assessment-network
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:cached
      - redis-data:/data:delegated